#server:
#  port = 9123
#
#spring:
#  datasource:
#    url = jdbc:mysql://localhost:3306/springboot
#    username = root
#    password =
#    driver-class-name = com.mysql.cj.jdbc.Driver
#  jpa:
#    database=mysql
#    database-platform=org.hibernate.dialect.MySQL57Dialect
#    hibernate.ddl-auto=update
#    show-mysql = true;